# APPLICATION
spring.application.name=Group05
server.port=8080

# DATABASE CONFIG (local overrides)
spring.datasource.url=jdbc:mysql://localhost:3306/group_05

spring.datasource.username=root
spring.datasource.password=RSStructuredquerylanguage3!

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JSP VIEW RESOLVER
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# OAUTH2 - GITHUB
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

spring.web.resources.static-locations=classpath:/static/,file:uploads/